### ISSUE TITLE
Create edit Item page

### ISSUE THREAD

**Issue by aledejesus** [aledejesus/item_catalog#25]

**Comment by aledejesus** [comment]
Remember to add a link to this page in /item/iid

**Comment by aledejesus** [comment]
**TODO:**
- [ ] create Item edit view
- [ ] populate form with item properties
- [ ] redirect to previous page when item does not exist
- [ ] flash error and information messages when appropriate
- [ ] check item add view as logic is very similar
- [ ] redirect to edited item page when editing is successful
- [ ] create Item edit HTML template
