### ISSUE TITLE
Create delete Item page

### ISSUE THREAD

**Issue by aledejesus** [aledejesus/item_catalog#26]
The page will have a message asking if the user is sure he/she wants to delete said item.

**Comment by aledejesus** [comment]
Remember to include a link to this page in /item/iid

**Comment by aledejesus** [comment]
**TODO:**
- [ ] create Item delete view
- [ ] verify that Item exists
- [ ] flash error and information messages when appropriate
- [ ] redirect to item category when deletion is successful
- [ ] create Item delete HTML template
- [ ] modify Item details page to include a button to this page
